I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    jump march_2_2
  File "game/script.rpy", line 8, in script
    jump march_2_2
ScriptError: could not find label 'march_2_2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "D:\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "D:\renpy-8.1.3-sdk\renpy\main.py", line 144, in run
    renpy.execution.run_context(True)
  File "D:\renpy-8.1.3-sdk\renpy\execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 8, in script
    jump march_2_2
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 8, in script
    jump march_2_2
  File "D:\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "D:\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'march_2_2'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
TheShadowoverInnsmouth 1.0
Sat Dec 23 23:52:38 2023
